apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
  name: girus
spec:
  containers:
  - image: alphine
    name: girus
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

