apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
  name: projetofinal
spec:
  containers:
  - image: nginx
    name: nginx
  - image: busybox
    name: busybox
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: primeiro-emptydir
    args:
      - sleep
      - "1800"
    resources: 
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
  volumes:
  - name: primeiro-emptydir
    emptyDir: 
      sizeLimit: "256Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}


