apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
  name: resourcelimits
spec:
  containers:
  - image: nginx
    name: nginx
    args:
      - sleep
      - "1800"
    resources: 
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

